name: CI-github-actions

on: 
  push:
  pull_request:

jobs:
  build-and-test:

    strategy:
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc
        
        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc
          
          - toolchain: macos-clang
            os: macos-latest
            compiler: clang

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc
      
    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Configure
      run: cmake -S . -Bbuild
    
    - name: Build with ${{ matrix.compiler }}
      run: cmake --build build

    - name: Test Linux-ish
      if: ${{ !contains(matrix.os, 'windows-latest') }}
      working-directory: build
      run: ./main
    
    - name: Test Windows
      if: ${{ contains(matrix.os, 'windows-latest') }}
      working-directory: build/Debug
      run: ./main.exe
    
    - name: Install
      run: cmake --install build